name: tests

on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo
          
      - name: Checkout pcb-versions repo
        uses: actions/checkout@v3
        with:
          repository: RaccoonLabHardware/pcb-versions
          token: ${{ secrets.ACCESS_TOKEN }}
          path: repo/pcb-versions

      - name: Check that all needed files exists (test-files-exists.py)
        run: |
          cd repo && python pcb-versions/test-files-exists.py

      - name: Generate dict BOMList from BOM file
        run: |
          cd repo && pip install openpyxl && python pcb-versions/test-generateBOM.py

      - name: Check Version Resistors is correct if exists (test-versions.py)
        run: |
          cd repo && python pcb-versions/test-versions.py

      - name: Check Manufacturer Partnumber (test-wrong-MP.py)
        run: |
          cd repo && python pcb-versions/test-wrong-MP.py

      - name: Check that all BOM components contains in 'pick and place' (test-BOM-PNP.py)
        run: |
          cd repo && pip install pandas && python pcb-versions/test-BOM-PNP.py      

      - name: All other tests that can be added in future
        run: |
          cd repo && pip install steputils && python pcb-versions/test-other.py